//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visit.CbisAPI.Categories {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://api.cbis.citybreak.com/")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int OrganizationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private int DefaultTemplateIdField;
        
        private Visit.CbisAPI.Categories.CategoryStatus StatusField;
        
        private System.Nullable<int> ParentCategoryIdField;
        
        private int DisplayOrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int OrganizationId {
            get {
                return this.OrganizationIdField;
            }
            set {
                if ((this.OrganizationIdField.Equals(value) != true)) {
                    this.OrganizationIdField = value;
                    this.RaisePropertyChanged("OrganizationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int DefaultTemplateId {
            get {
                return this.DefaultTemplateIdField;
            }
            set {
                if ((this.DefaultTemplateIdField.Equals(value) != true)) {
                    this.DefaultTemplateIdField = value;
                    this.RaisePropertyChanged("DefaultTemplateId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public Visit.CbisAPI.Categories.CategoryStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ParentCategoryId {
            get {
                return this.ParentCategoryIdField;
            }
            set {
                if ((this.ParentCategoryIdField.Equals(value) != true)) {
                    this.ParentCategoryIdField = value;
                    this.RaisePropertyChanged("ParentCategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int DisplayOrder {
            get {
                return this.DisplayOrderField;
            }
            set {
                if ((this.DisplayOrderField.Equals(value) != true)) {
                    this.DisplayOrderField = value;
                    this.RaisePropertyChanged("DisplayOrder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryStatus", Namespace="http://api.cbis.citybreak.com/")]
    public enum CategoryStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Inactive = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeOfCategory", Namespace="http://api.cbis.citybreak.com/")]
    [System.SerializableAttribute()]
    public partial class TreeOfCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Visit.CbisAPI.Categories.TreeNodeOfCategory[] NodesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Visit.CbisAPI.Categories.TreeNodeOfCategory[] Nodes {
            get {
                return this.NodesField;
            }
            set {
                if ((object.ReferenceEquals(this.NodesField, value) != true)) {
                    this.NodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TreeNodeOfCategory", Namespace="http://api.cbis.citybreak.com/")]
    [System.SerializableAttribute()]
    public partial class TreeNodeOfCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Visit.CbisAPI.Categories.Category DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Visit.CbisAPI.Categories.TreeNodeOfCategory[] ChildrenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Visit.CbisAPI.Categories.Category Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Visit.CbisAPI.Categories.TreeNodeOfCategory[] Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.cbis.citybreak.com/", ConfigurationName="Categories.CategoriesSoap")]
    public interface CategoriesSoap {
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.cbis.citybreak.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.cbis.citybreak.com/GetById", ReplyAction="*")]
        Visit.CbisAPI.Categories.GetByIdResponse GetById(Visit.CbisAPI.Categories.GetByIdRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.cbis.citybreak.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.cbis.citybreak.com/ListAll", ReplyAction="*")]
        Visit.CbisAPI.Categories.ListAllResponse ListAll(Visit.CbisAPI.Categories.ListAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://api.cbis.citybreak.com/", Order=0)]
        public Visit.CbisAPI.Categories.GetByIdRequestBody Body;
        
        public GetByIdRequest() {
        }
        
        public GetByIdRequest(Visit.CbisAPI.Categories.GetByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.cbis.citybreak.com/")]
    public partial class GetByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int languageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int categoryId;
        
        public GetByIdRequestBody() {
        }
        
        public GetByIdRequestBody(string apiKey, int languageId, int categoryId) {
            this.apiKey = apiKey;
            this.languageId = languageId;
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://api.cbis.citybreak.com/", Order=0)]
        public Visit.CbisAPI.Categories.GetByIdResponseBody Body;
        
        public GetByIdResponse() {
        }
        
        public GetByIdResponse(Visit.CbisAPI.Categories.GetByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.cbis.citybreak.com/")]
    public partial class GetByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Visit.CbisAPI.Categories.Category GetByIdResult;
        
        public GetByIdResponseBody() {
        }
        
        public GetByIdResponseBody(Visit.CbisAPI.Categories.Category GetByIdResult) {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAll", Namespace="http://api.cbis.citybreak.com/", Order=0)]
        public Visit.CbisAPI.Categories.ListAllRequestBody Body;
        
        public ListAllRequest() {
        }
        
        public ListAllRequest(Visit.CbisAPI.Categories.ListAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.cbis.citybreak.com/")]
    public partial class ListAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int languageId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int parentCategoryId;
        
        public ListAllRequestBody() {
        }
        
        public ListAllRequestBody(string apiKey, int languageId, int parentCategoryId) {
            this.apiKey = apiKey;
            this.languageId = languageId;
            this.parentCategoryId = parentCategoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAllResponse", Namespace="http://api.cbis.citybreak.com/", Order=0)]
        public Visit.CbisAPI.Categories.ListAllResponseBody Body;
        
        public ListAllResponse() {
        }
        
        public ListAllResponse(Visit.CbisAPI.Categories.ListAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.cbis.citybreak.com/")]
    public partial class ListAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Visit.CbisAPI.Categories.TreeOfCategory ListAllResult;
        
        public ListAllResponseBody() {
        }
        
        public ListAllResponseBody(Visit.CbisAPI.Categories.TreeOfCategory ListAllResult) {
            this.ListAllResult = ListAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface CategoriesSoapChannel : Visit.CbisAPI.Categories.CategoriesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CategoriesSoapClient : System.ServiceModel.ClientBase<Visit.CbisAPI.Categories.CategoriesSoap>, Visit.CbisAPI.Categories.CategoriesSoap {
        
        public CategoriesSoapClient() {
        }
        
        public CategoriesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CategoriesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CategoriesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Visit.CbisAPI.Categories.GetByIdResponse Visit.CbisAPI.Categories.CategoriesSoap.GetById(Visit.CbisAPI.Categories.GetByIdRequest request) {
            return base.Channel.GetById(request);
        }
        
        public Visit.CbisAPI.Categories.Category GetById(string apiKey, int languageId, int categoryId) {
            Visit.CbisAPI.Categories.GetByIdRequest inValue = new Visit.CbisAPI.Categories.GetByIdRequest();
            inValue.Body = new Visit.CbisAPI.Categories.GetByIdRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.languageId = languageId;
            inValue.Body.categoryId = categoryId;
            Visit.CbisAPI.Categories.GetByIdResponse retVal = ((Visit.CbisAPI.Categories.CategoriesSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Visit.CbisAPI.Categories.ListAllResponse Visit.CbisAPI.Categories.CategoriesSoap.ListAll(Visit.CbisAPI.Categories.ListAllRequest request) {
            return base.Channel.ListAll(request);
        }
        
        public Visit.CbisAPI.Categories.TreeOfCategory ListAll(string apiKey, int languageId, int parentCategoryId) {
            Visit.CbisAPI.Categories.ListAllRequest inValue = new Visit.CbisAPI.Categories.ListAllRequest();
            inValue.Body = new Visit.CbisAPI.Categories.ListAllRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.languageId = languageId;
            inValue.Body.parentCategoryId = parentCategoryId;
            Visit.CbisAPI.Categories.ListAllResponse retVal = ((Visit.CbisAPI.Categories.CategoriesSoap)(this)).ListAll(inValue);
            return retVal.Body.ListAllResult;
        }
    }
}
